import styles from "@styles/design-system.module.css";
import {
  MAP_GRID,
  MAP_GRID_ITEM,
  MAP_SHOP,
  MAP_EMPTY,
} from "@pages/index.classnames";

const Cartography = () => {
  return (
    <div>
      <h1>Cartography</h1>

      <div className={MAP_GRID}>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_SHOP}></div>
        <div className={MAP_EMPTY}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
        <div className={MAP_GRID_ITEM}></div>
      </div>
    </div>
  );
};

export default Cartography;
